# 配置服务器端口，默认是8080，可以不用配置
server:
  port: 8080

#spring相关配置
spring:
  #配置前端模板thymeleaf
  thymeleaf:
    mode: LEGACYHTML5 #thymeleaf松校验
    encoding: utf-8
    cache: false #关闭缓存，避免改了模板还需要重新启动项目

  #配置数据库连接源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/o2o?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  #配置mybatis
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.dyl.o2o.domain

