# 配置服务器端口，默认是8080，可以不用配置
server:
  port: 8080

#spring相关配置
spring:
  #配置前端模板thymeleaf
  thymeleaf:
    mode: LEGACYHTML5 #thymeleaf松校验
    encoding: utf-8
    cache: false #关闭缓存，避免改了模板还需要重新启动项目

  #配置数据库连接源
  datasource:
    master:
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/o2o?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/o2o?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#      jdbc-url: jdbc:mysql://localhost:3307/o2o?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver

  #开发工具
  devtools:
    restart:
      enabled: true #开启热部署
  freemarker:
    cache: false #页面不加载，修改即生效

  #Redis缓存
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-wait: 30000   #连接池最大阻塞事件（负值为无限制，默认-1）单位毫秒
        max-active: 30  #连接池最大连接数（负值为无限制，默认8）
        max-idle: 20  #连接池最大空闲连接数（负值为无限制，默认8）
        min-idle: 10  #连接池中最小空闲连接（默认为0）
    timeout: 3000   #连接超时时间（单位ms）



#JWT配置
jwt:
  #密钥
  secret: dyljwt
  #HeaderKEY
  tokenHeader: Authorization
  #Token前缀字符
  tokenPrefix: Bearer
  #过期时间 单位秒 1小时：3600 1天：86400 7天：604800
  expiration: 86400


#设置日志相关
logging:
  level:
    root: info
    com.dyl.o2o.dao: debug
  path: ./log